//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriesTable()
        {
            this.AdditionalInfo = new HashSet<AdditionalInfo>();
        }
    
        public int IDCategories { get; set; }
        public bool A { get; set; }
        public bool B { get; set; }
        public bool BE { get; set; }
        public bool C { get; set; }
        public bool CE { get; set; }
        public bool D { get; set; }
        public bool DE { get; set; }
        public bool M { get; set; }
        public bool TM { get; set; }
        public bool TB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalInfo> AdditionalInfo { get; set; }
    }
}
