//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education()
        {
            this.Guest = new HashSet<Guest>();
        }
    
        public int IDEducation { get; set; }
        public string EducationalInstitution { get; set; }
        public string Faculty { get; set; }
        public string Specialization { get; set; }
        public int IDYearOfGraduation { get; set; }
        public int IDEducationalForm { get; set; }
    
        public virtual YearOfGraduation YearOfGraduation { get; set; }
        public virtual EducationForm EducationForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guest { get; set; }
    }
}
