//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int IDGuest { get; set; }
        public Nullable<int> IDBasicInfo { get; set; }
        public Nullable<int> IDPersonalInfo { get; set; }
        public Nullable<int> IDExperience { get; set; }
        public Nullable<int> IDEducation { get; set; }
        public Nullable<int> IDCousersAndTrainings { get; set; }
        public Nullable<int> IDITSkills { get; set; }
        public Nullable<int> IDAdditionalInfo { get; set; }
    
        public virtual AdditionalInfo AdditionalInfo { get; set; }
        public virtual BasicInfo BasicInfo { get; set; }
        public virtual CousersAndTrainings CousersAndTrainings { get; set; }
        public virtual Education Education { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual ITSkills ITSkills { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
