//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int IDGuest { get; set; }
        public byte[] Pic { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Post { get; set; }
        public decimal DesiredSalary { get; set; }
        public int IDBusyness { get; set; }
        public int IDWorkPlan { get; set; }
        public Nullable<int> BusinessTrips { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CityOfResidence { get; set; }
        public int IDMovement { get; set; }
        public string Citizenship { get; set; }
        public System.DateTime Birthday { get; set; }
        public int IDSex { get; set; }
        public int IDFamilyStatus { get; set; }
        public bool Kids { get; set; }
        public int IDLearning { get; set; }
        public int IDExperience { get; set; }
        public Nullable<int> IDEducation { get; set; }
        public Nullable<int> IDCousersAndTrainings { get; set; }
        public int IDITSkills { get; set; }
        public int IDAdditionalInfo { get; set; }
    
        public virtual AdditionalInfo AdditionalInfo { get; set; }
        public virtual Busyness Busyness { get; set; }
        public virtual CousersAndTrainings CousersAndTrainings { get; set; }
        public virtual Education Education { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual FamilyStatus FamilyStatus { get; set; }
        public virtual ITSkills ITSkills { get; set; }
        public virtual Learning Learning { get; set; }
        public virtual Movement Movement { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual WorkPlan WorkPlan { get; set; }
    }
}
