//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeEntities : DbContext
    {
        public ResumeEntities()
            : base("name=ResumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalInfo> AdditionalInfo { get; set; }
        public virtual DbSet<BasicInfo> BasicInfo { get; set; }
        public virtual DbSet<BusynessTable> BusynessTable { get; set; }
        public virtual DbSet<CategoriesTable> CategoriesTable { get; set; }
        public virtual DbSet<CousersAndTrainings> CousersAndTrainings { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<EducationFormTable> EducationFormTable { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<FamilyStatusTable> FamilyStatusTable { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<ITSkills> ITSkills { get; set; }
        public virtual DbSet<LearningTable> LearningTable { get; set; }
        public virtual DbSet<MovementTable> MovementTable { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfo { get; set; }
        public virtual DbSet<SexTable> SexTable { get; set; }
        public virtual DbSet<SubcategoriesTable> SubcategoriesTable { get; set; }
        public virtual DbSet<WorkPlanTable> WorkPlanTable { get; set; }
        public virtual DbSet<YearOfGraduationTable> YearOfGraduationTable { get; set; }
    }
}
