//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalInfo> AdditionalInfo { get; set; }
        public virtual DbSet<Busyness> Busyness { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CousersAndTrainings> CousersAndTrainings { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<EducationForm> EducationForm { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<FamilyStatus> FamilyStatus { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<ITSkills> ITSkills { get; set; }
        public virtual DbSet<Learning> Learning { get; set; }
        public virtual DbSet<Movement> Movement { get; set; }
        public virtual DbSet<Proficiency> Proficiency { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<WorkPlan> WorkPlan { get; set; }
        public virtual DbSet<YearOfGraduation> YearOfGraduation { get; set; }
    }
}
