//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalInfo()
        {
            this.Guest = new HashSet<Guest>();
        }
    
        public int IDPersonalInfo { get; set; }
        public string CityOfResidence { get; set; }
        public int IDMovement { get; set; }
        public string Citizenship { get; set; }
        public System.DateTime Birthday { get; set; }
        public int IDSex { get; set; }
        public int IDFamilyStatus { get; set; }
        public bool Kids { get; set; }
        public int IDLearning { get; set; }
    
        public virtual FamilyStatusTable FamilyStatusTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guest { get; set; }
        public virtual LearningTable LearningTable { get; set; }
        public virtual MovementTable MovementTable { get; set; }
        public virtual SexTable SexTable { get; set; }
    }
}
