//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.V.ResumeWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubcategoriesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubcategoriesTable()
        {
            this.AdditionalInfo = new HashSet<AdditionalInfo>();
        }
    
        public int IDSubcategories { get; set; }
        public bool A1 { get; set; }
        public bool B1 { get; set; }
        public bool C1 { get; set; }
        public bool C1E { get; set; }
        public bool D1 { get; set; }
        public bool D1E { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalInfo> AdditionalInfo { get; set; }
    }
}
